# Generated by Django 2.1.7 on 2019-02-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
    ]
