# Generated by Django 2.1.7 on 2019-02-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0005_auto_20190218_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('ingredients', models.ManyToManyField(to='ingredient.Ingredient')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
